# railway.toml

[project]
name = "library"

[build]
# Backend (Express)
[build.backend]
command = "cd backend && npm install"

# Frontend (React)
[build.frontend]
command = "cd frontend && npm install && npm run build"

[start]
# Backend (Express)
[start.backend]
command = "cd backend && npm run start"
service = "backend"
env = "node"

# Frontend (React)
[start.frontend]
command = "cd frontend && npm install && npm run start"
service = "frontend"
env = "node"
